services:
  - type: web
    name: campus-compass-api
    env: python
    plan: free
    region: oregon

    rootDir: backend

    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt -c constraints.txt

    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT

    autoDeploy: true
    healthCheckPath: /

    envVars:
      - key: PINECONE_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: REDIS_URL
        sync: false
      - key: REDIS_PASSWORD
        sync: false
      - key: PINECONE_INDEX_NAME
        value: campus-assistant
      - key: STORAGE_BUCKET_NAME
        value: college-documents
      - key: PYTHON_VERSION
        value: 3.12.10
